#! /bin/sh

bspc config focused_border_color    #A3BE8C
bspc config normal_border_color     #3B4252
bspc config window_gap              24
bspc config top_padding             15
bspc config border_width            1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
# bspc config focus_follows_pointer   true

# bspc monitor DVI-I-2 -d I II III IV V
# bspc monitor DVI-I-3 -d VI VII VIII IX X
MONITORS=($(xrandr -q | grep '\bconnected\b' | sort -t '+' -nk2 | awk '{print $1}'))
for i in ${!MONITORS[@]}; do
    n=$[i * 3]
    bspc monitor ${MONITORS[$i]} -d $[n + 1] $[n + 2] $[n + 3];
    # bspc monitor ${MONITORS[$i]} -d 1 2 3 4 5;
done
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# ~/.panel/panel &
# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch main bar
polybar --reload main-bar &
