#! /bin/sh

# Windows and borders
bspc config focused_border_color    "#EBCB8B"
bspc config normal_border_color     "#3B4252"
bspc config window_gap              24
bspc config top_padding             15
bspc config border_width            1
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Multihead behaviour
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behaviour
# bspc config click_to_focus          true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config focus_by_distance       true

MONITORS=($(xrandr -q | grep '\bconnected\b' | sort -t '+' -nk2 | awk '{print $1}'))
for i in ${!MONITORS[@]}; do
    n=$[i * 3]
    bspc monitor ${MONITORS[$i]} -d $[n + 1] $[n + 2] $[n + 3];
done
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch_panels.sh
