#! /bin/sh

xsetroot -cursor_name left_ptr &

# Windows and borders
bspc config focused_border_color    "#EBCB8B"
bspc config normal_border_color     "#3B4252"
bspc config window_gap              24
bspc config top_padding             15
bspc config border_width            0
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Multihead behaviour
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behaviour
# bspc config click_to_focus          true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config focus_by_distance       true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner

MONITORS=($(xrandr -q | grep '\bconnected\b' | sort -t '+' -nk2 | awk '{print $1}'))
for i in ${!MONITORS[@]}; do
    n=$[i * 5]
    bspc monitor ${MONITORS[$i]} -d $[n + 1] $[n + 2] $[n + 3] $[n + 4] $[n + 5];
done

bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a '*:zathura' state=tiled

$HOME/.config/polybar/launch_panels.sh
